### ISSUE TITLE
プールページに貸出率貸借金利グラフの作成

### ISSUE THREAD

**Issue by naizo01** [DeFiGeek-Community/comet-interface#17]
**説明**:
プールページに、貸出率貸借金利グラフを追加します。
CompoundのInterest Rate Modelグラフを参考にし、react-chartjs-2などのライブラリを使用して作成します。

**タスク**:

   - CompoundのInterest Rate Modelグラフを参考
   - react-chartjs-2などのグラフライブラリを使用して、グラフコンポーネントを作成
   - レスポンシブデザインに対応
   - 現在の画面はグラフ配置を考慮されていないため、画面構成の検討が必要
   - 必要に応じて、ページレイアウトや他の要素の配置を調整が必要

実装サポートはします。

**Comment by YosukeMiyata** [comment]
実装完了！
