### ISSUE TITLE
Liquidation Limitのステータスバー改善

### ISSUE THREAD

**Issue by naizo01** [DeFiGeek-Community/comet-interface#5]
**内容**:
プール利用者の状況を直感的に理解できるよう、ステータスバーに以下の機能を実装します。

**機能要件**:
1. **総担保額の表示**: ステータスバーの最大値をユーザーの総担保額として設定。
2. **LCFの合計表示**: 赤い点またはドクロマークで表示し、リスクが高いことを示す。
3. **CFの合計表示**: 黄色い点で表示し、警告レベルを示す。
4. **borrow額の色分け**:
   - CFの80%未満: 緑色で安全範囲を示す。
   - CFの80%以上: 黄色で警告範囲を示す。
   - CFを超える場合: 赤色で危険範囲を示す。

**技術的課題**:
現在使用している`@chakra-ui/react`のコンポーネントでは上記の機能要件を満たせません。解決策として、以下の2つのアプローチを考えています。

1. **新しいライブラリの探索**: 必要な機能を提供する既存のライブラリがあれば導入する。
2. **CSSによるカスタム実装**: レスポンシブ対応を含め、すべての表示要件を自分でCSSを使用して実装する。

どちらの方法も、スマートフォンサイズを含むレスポンシブデザインに対応する必要があります。カスタム実装にはかなりの労力が必要です。

**要望**:
上記の要件に対応可能なライブラリの調査も含めてお願いします。

**Comment by YosukeMiyata** [comment]
2024年5月に実装が完了いたしました！
